apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  annotations:
    tekton.dev/signature: MEUCIQDrTulLk2mjByvESr7WQBZeEiONOVNNhLhe4dpUq9NveQIgBCEp27HgMgS9KjIwGM9T+rXs7gkl9ZMuEiBdYZgIY7Y=
  creationTimestamp: null
  name: example-pipeline
  namespace: trusted-resources
spec:
  tasks:
  - name: example-task
    taskRef:
      params:
      - name: url
        value: https://github.com/Yongxuanzhang/sample-tekton-resources-cosign
      - name: revision
        value: main
      - name: pathInRepo
        value: signed-kms.yaml
      resolver: git
